### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by roscale** [0v3rl0w/Jcrypt#2]
I can't figure out how to use this program.

**Comment by 0v3rl0w** [comment]
It's a python module just install it with the command

> python3 setup.py install

and then in your python code you just have to import it ;) 

Have a nice day

**Comment by 0v3rl0w** [comment]
Here is the functionality list: https://github.com/0v3rl0w/Jcrypt/blob/master/function.md

**Comment by roscale** [comment]
Much better ^^, thank you.
