### ISSUE TITLE
No issue or not...

### ISSUE THREAD

**Issue by loic2665** [0v3rl0w/Jcrypt#3]
All is working fine. Thanks.

No, that false. 

`>>> from Jcrypt import *
>>> crypt("hey")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'crypt' is not defined`

What is wrong ?

**Comment by 0v3rl0w** [comment]
Hello @loic2665 Thanks for your report. Here's how you can fixe that. Open a terminal window and than go where you've cloned Jcrypt, then type this line:

```
sudo pip install -e .
```
